### ISSUE TITLE
[Utils/markdown_parser] Ошибка парсинга блоков кода в GPT

### ISSUE THREAD

**Issue by Xoma163** [Xoma163/petrovich#713]
![image](https://i.imgur.com/V5VRuDI.jpeg)

Ишю от пользователя Евгений Дубовицкий (id=91)
Данное ишю сгенерировано автоматически

**Comment by Xoma163** [comment]
бля

**Comment by edubovit** [comment]
ещё кейс
![image](https://github.com/Xoma163/petrovich/assets/5397167/cb9f6bc3-5fbb-42fd-bf15-7b0b7eff1b7a)
