### ISSUE TITLE
Не работает аплоад с Твиттера

### ISSUE THREAD

**Issue by Xoma163** [Xoma163/petrovich#820]
![image](https://i.imgur.com/k83yNNX.png)

Ишю от пользователя Евгений Дубовицкий (id=91)
Данное ишю сгенерировано автоматически

**Comment by edubovit** [comment]
Туда же

https://x.com/majeliskucing/status/1808668549139026104

**Comment by edubovit** [comment]
Почему-то не подхватилась линка из первого поста

https://x.com/juliamayko/status/1808913934952321125

**Comment by Xoma163** [comment]
![image](https://github.com/Xoma163/petrovich/assets/35608430/67eccb84-e053-4d28-b94c-fbccf85b9058)

**Comment by Xoma163** [comment]
та хз апиха лаганула, щас всё работает

> Почему-то не подхватилась линка из первого поста
> 
> https://x.com/juliamayko/status/1808913934952321125

не понял

**Comment by edubovit** [comment]
Да, всё гуд
