### ISSUE TITLE
[Twitter] Не трансформирует видео

### ISSUE THREAD

**Issue by Xoma163** [Xoma163/petrovich#865]
https://x.com/depressionlesss/status/1837748874032689317

Ишю от пользователя Евгений Дубовицкий (id=91)
Данное ишю сгенерировано автоматически

**Comment by edubovit** [comment]
![petrovich_logs (13)](https://github.com/user-attachments/assets/e4d12ad3-c705-4018-8635-e1c561b4fb97)

**Comment by Xoma163** [comment]
![Screenshot_20240922_171543.jpg](https://github.com/user-attachments/assets/8901b65c-12f5-4461-a17c-969e78661932)

**Comment by Xoma163** [comment]
Обработку исключения сделалъ. Гляну мб есть провайдеры где побольше бесплатных запросов в месяц есть

**Comment by Xoma163** [comment]
Короче, Меченый, я тебе апиху новую прикрутил и в благородство играть не буду: выполнишь для меня пару заданий — и мы в расчете. Заодно посмотрим, как быстро у тебя башка после твиттерного голодания прояснится. А по твоей теме постараюсь разузнать. Хрен его знает, на кой ляд тебе этот твиттер сдался, но я в чужие дела не лезу, хочешь слать посты, значит есть за что...

P.S. Апиху прикрутил. 3к запросов в месяц + экономия на --threads, потому что теперь оно всё одним запросом собирается. Обработка тредов работает, но не факт, что корректно. Тут немного другая структура, в которой я до конца не разобрался. Картинки и видео проверил, работает. Но бывают пролетают те же самые ссылки, которые телеге не нравятся. Это не проблема апихи, это проблема телеги
